use_frameworks!

platform :ios, '9.0'

target 'CMAlgorithmKit_Example' do
  pod 'CMAlgorithmKit', :path => '../'

  target 'CMAlgorithmKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
